version: '3.4'

services:
  finance.api:
    image: ${DOCKER_REGISTRY-}financeapi
    container_name: Finance.Api
    build:
      context: .
      dockerfile: src/Finance.Api/Dockerfile
    depends_on:
      finance-db:
        condition: service_healthy
    links:
      - finance-db
    networks:
      - postgres

  finance-db:
    image: postgres:17
    container_name: Finance.Db
    environment:
      POSTGRES_DB: finance
      POSTGRES_USER: olliver
      POSTGRES_PASSWORD: q1w2e3r4
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U olliver -d finance"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s

  finance-idp:
    image: keycloak/keycloak:latest
    container_name: Finance.Identity
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files/finance-realm-export.json:/opt/keycloak/data/import/finance-realm-export.json
    ports:
      - 18080:8080
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: teste@teste.com
      PGADMIN_DEFAULT_PASSWORD: q1w2e3r4
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
       - ./.containers/pgadmin:/var/lib/pgadmin

    ports:
      - "8082:80"
    networks:
      - postgres
    restart: unless-stopped
  finance-seq:
    image: datalust/seq:latest
    container_name: Finance.Seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_NOAUTHENTICATION=true
    ports:
      - 5431:5341
      - 8083:80
    networks:
      - postgres

networks:
  postgres:
    driver: bridge